<a href="https://colab.research.google.com/github/Kacp3rRingil/Data-science-Udemy-course/blob/main/01_course/01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [57]:
import numpy as np
np.__version__

'1.22.4'

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

1D Array

In [ ]:
x = np.array([1, 3])
x

array([1, 3])

In [ ]:
print(x)
type(x)

[1 3]


numpy.ndarray

In [ ]:
x.ndim

1

In [ ]:
x.shape

(2,)

In [ ]:
x.size

2

In [ ]:
x.dtype

dtype('int64')

In [ ]:
np.array([1.2, 2.3, 3.1])
print(x)
x.dtype

[1 3]


dtype('int64')

2D Array

In [ ]:
x = np.array([[1, 2], [-3, 1]])
x

array([[ 1,  2],
       [-3,  1]])

In [ ]:
x.ndim

2

In [ ]:
x.shape

(2, 2)

In [ ]:
x.dtype

dtype('int64')

In [ ]:
x = np.array([[1, 2, 4], [4, 2, 1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [ ]:
x.shape

(2, 3)

3D Array

In [ ]:
x = np.array(
    [[[4, 3, 1],
      [3, 1, 2]],
     
     [[4, 1, 3],
      [4, 2, 1]]]
)
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]]])

In [ ]:
x.ndim 

3

In [ ]:
x.shape

(2, 2, 3)

Typy Danych

In [ ]:
A = np.array([1, 2, 3], dtype = "float")
A.dtype

dtype('float64')

In [ ]:
A = np.array([1.0, 2.3, 3.6])
A.dtype

dtype('float64')

In [ ]:
A = np.array([1.0, 2.3, 3.6], dtype = "float")
A.dtype

dtype('float64')

In [ ]:
A = np.array([1.0, 2.3, 3.6], dtype = "complex")
A.dtype

dtype('complex128')

In [ ]:
A

array([1. +0.j, 2.3+0.j, 3.6+0.j])

In [ ]:
A = np.array([1.0, 2.3, 3.6], dtype = "int")
A.dtype

dtype('int64')

In [ ]:
A

array([1, 2, 3])

In [ ]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [ ]:
A = np.array([24, 120, 230], dtype = np.int8)
A.dtype

dtype('int8')

Tworzenie tablic

In [ ]:
np.zeros(shape = (4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.zeros(shape = (4, 10), dtype = "int")

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
np.ones(shape = (5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.ones(shape = (5, 5), dtype = "int")

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
np.full(shape = (3, 3), fill_value= 4, dtype = "int")

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(start = 5, stop = 10)

array([5, 6, 7, 8, 9])

In [ ]:
np.arange(start = 10, stop = 100, step = 10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
np.arange(start = 100, stop = 10, step = -10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [ ]:
np.arange(start = 0, stop = 1, step = 0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [ ]:
np.linspace(start = 0, stop =1, num = 50)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [6]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [7]:
A.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [12]:
A.reshape((3, -1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [13]:
A.reshape((-1, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

Podstawowe operacje na tablicach

In [14]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [15]:
A+B

array([6, 0, 7, 4])

In [16]:
A - B

array([0, 2, 1, 0])

In [17]:
A * B

array([ 9, -1, 12,  4])

In [20]:
C = A / B


[ 1.         -1.          1.33333333  1.        ]


In [26]:
np.add(A, B)

array([6, 0, 7, 4])

In [27]:
np.subtract(A , B)

array([0, 2, 1, 0])

In [28]:
np.multiply(A, B)

array([ 9, -1, 12,  4])

In [29]:
np.divide(A, B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [22]:
A + 3

array([6, 4, 7, 5])

In [23]:
A - 3

array([ 0, -2,  1, -1])

In [24]:
A * 2

array([6, 2, 8, 4])

In [25]:
A + 2 * B

array([ 9, -1, 10,  6])

In [32]:
X = np.array([[1, 3], [-2, 0]])

Y = np.array([[6, 0], [-1, 2]])
print(X, "\n")
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [33]:
X * Y

array([[6, 0],
       [2, 0]])

In [34]:
np.dot(X, Y)

array([[  3,   6],
       [-12,   0]])

In [35]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [36]:
Y.dot(Y)

array([[36,  0],
       [-8,  4]])

In [37]:
X @ Y

array([[  3,   6],
       [-12,   0]])

Generowanie liczb pseudolosowych

In [38]:
np.random.seed(0)

In [45]:
np.random.randn(10)

array([ 0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357,
        1.45427351,  0.76103773,  0.12167502,  0.44386323,  0.33367433])

In [46]:
np.random.randn(10,4)

array([[ 1.49407907, -0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 , -0.74216502],
       [ 2.26975462, -1.45436567,  0.04575852, -0.18718385],
       [ 1.53277921,  1.46935877,  0.15494743,  0.37816252],
       [-0.88778575, -1.98079647, -0.34791215,  0.15634897],
       [ 1.23029068,  1.20237985, -0.38732682, -0.30230275],
       [-1.04855297, -1.42001794, -1.70627019,  1.9507754 ],
       [-0.50965218, -0.4380743 , -1.25279536,  0.77749036],
       [-1.61389785, -0.21274028, -0.89546656,  0.3869025 ],
       [-0.51080514, -1.18063218, -0.02818223,  0.42833187]])

In [52]:
np.random.rand()

0.1201965612131689

In [53]:
np.random.rand(10, 4)

array([[0.2961402 , 0.11872772, 0.31798318, 0.41426299],
       [0.0641475 , 0.69247212, 0.56660145, 0.26538949],
       [0.52324805, 0.09394051, 0.5759465 , 0.9292962 ],
       [0.31856895, 0.66741038, 0.13179786, 0.7163272 ],
       [0.28940609, 0.18319136, 0.58651293, 0.02010755],
       [0.82894003, 0.00469548, 0.67781654, 0.27000797],
       [0.73519402, 0.96218855, 0.24875314, 0.57615733],
       [0.59204193, 0.57225191, 0.22308163, 0.95274901],
       [0.44712538, 0.84640867, 0.69947928, 0.29743695],
       [0.81379782, 0.39650574, 0.8811032 , 0.58127287]])

In [55]:
np.random.randint(10)

9

In [58]:
np.random.randint(low = 10, high = 101, size = 10)

array([70, 71, 93, 43, 42, 80, 95, 41, 23, 81])

In [65]:
np.random.choice([4, 2, 1, 2])

1

In [67]:
np.random.choice(["python", "java", "sql"])

'sql'

In [68]:
data = np.arange(10)
data


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
np.random.shuffle(data)
data

array([3, 7, 9, 2, 4, 1, 0, 6, 8, 5])

Podstawowe funkcje

In [77]:
np.exp(1)

2.718281828459045

In [80]:
np.exp(4)

54.598150033144236

In [81]:
np.sqrt(9)

3.0

In [83]:
np.all([2, 3, 1])

True

In [87]:
np.any([0, 0, 0])

False

In [94]:
bool(0)

False

In [95]:
bool(1)

True

In [98]:
A = np.random.rand(5)
A

array([0.45354268, 0.7220556 , 0.86638233, 0.97552151, 0.85580334])

In [99]:
np.argmax(A)

3

In [101]:
A[np.argmax(A)]

0.9755215050028858

In [102]:
np.argmin(A)

0

In [103]:
np.argsort(A)

array([0, 1, 4, 2, 3])

In [104]:
np.max(A)

0.9755215050028858

In [106]:
np.min(A)

0.45354268267806885

In [108]:
np.mean(A)

0.7746610910945086

In [110]:
np.median(A)

0.855803342392611

In [111]:
np.std(A)

0.179569555166566

Indeksowanie, Wycinanie

In [112]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [113]:
#A[0], A[start:stop] , A[:stop], A[start:]

In [114]:
A[2]

2

In [116]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [117]:
A[:2]

array([0, 1])

In [120]:
A[[0,2]]

array([0, 2])

In [122]:
A[-1]

19

In [123]:
A[10:15]

array([10, 11, 12, 13, 14])

In [125]:
A = A.reshape(4, 5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [127]:
A[0]

array([0, 1, 2, 3, 4])

In [129]:
A[1]

array([5, 6, 7, 8, 9])

In [133]:
A[:, -1]

array([ 4,  9, 14, 19])

In [134]:
A[1, 1]

6

In [135]:
A[1, 3]

8

In [137]:
A[1:3, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [139]:
A[1, 2] = 14
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

Iteracja po tablicach

In [140]:
for row in A:
  print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [141]:
for row in A:
  print(row[0])

0
5
10
15


In [142]:
for row in A:
  print(row[:3])

[0 1 2]
[ 5  6 14]
[10 11 12]
[15 16 17]


In [143]:
for row in A:
  print(row[1:3])

[1 2]
[ 6 14]
[11 12]
[16 17]


In [144]:
for item in A.flat:
  print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


Zmiana rozmiaru tablic

In [145]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [146]:
A.shape

(4, 5)

In [147]:
A.reshape(5, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [148]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [149]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

Maski logiczne

In [150]:
A = np.arange(start = -10, stop= 10, step = 0.5)
A

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,  -5. ,  -4.5,  -4. ,  -3.5,  -3. ,  -2.5,  -2. ,  -1.5,
        -1. ,  -0.5,   0. ,   0.5,   1. ,   1.5,   2. ,   2.5,   3. ,
         3.5,   4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ,   7.5,
         8. ,   8.5,   9. ,   9.5])

In [152]:
A = A.reshape(10, -1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [153]:
A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [154]:
A[A > 0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [156]:
np.bitwise_and(A > -5, A < 5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [159]:
A[np.bitwise_and(A > -5, A < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [160]:
np.bitwise_or(A < -5, A > 5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])