<a href="https://colab.research.google.com/github/Kacp3rRingil/Data-science-Udemy-course/blob/main/01_course/02_algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
np.__version__

'1.22.4'

Norma wektora

In [ ]:
v1 = np.array([0, 4])
v1

array([0, 4])

In [ ]:
np.linalg.norm(v1)

4.0

Norma euklidesowa

In [2]:
v2 = np.array([-10, 10, 13])
np.linalg.norm(v2)

19.209372712298546

Odległość 2 pkt na płaszczyźnie

In [3]:
p = np.array([3, 0])
q = np.array([0, 4])

np.linalg.norm(p - q)

5.0

Odleglosc 2 pkt w przestrzenie R3

In [4]:
p = np.array([3, 0, 1])
q = np.array([0, 4, 2])

np.linalg.norm(p - q)

5.0990195135927845

Mnozenie Macierzy

In [7]:
X = np.array([[5, 3], [3, 9]])
Y = np.array([[1], [-1]])
print(X, "\n")
print(Y)

[[5 3]
 [3 9]] 

[[ 1]
 [-1]]


In [8]:
Z = np.dot(X, Y)
Z

array([[ 2],
       [-6]])

In [9]:
Z.shape

(2, 1)

In [11]:
X = np.array([[2, -1, 3], 
              [3, 1, 0]])
Y = np.array([[2, 1, -1],
              [0, -1, 2],
              [3, 2, 0]])
print(X, "\n")
print(Y)

[[ 2 -1  3]
 [ 3  1  0]] 

[[ 2  1 -1]
 [ 0 -1  2]
 [ 3  2  0]]


In [12]:
np.dot(X, Y)

array([[13,  9, -4],
       [ 6,  2, -1]])

Wyznacznik macierzy

In [13]:
A = np.array([[2, 4], [-1, 3]])
np.linalg.det(A)

9.999999999999998

In [15]:
round(np.linalg.det(A))

10

Ślad macierzy

In [16]:
A = np.array([[2, 4], [-1, 3]])
np.trace(A)

5

Macierz jednostkowa

In [17]:
np.eye(5, dtype = "int")

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [18]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Macierz odwrotna

In [24]:
B = np.linalg.inv(A)
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [27]:
np.set_printoptions(precision = 4, suppress = True)

np.dot(A ,B)

array([[1., 0.],
       [0., 1.]])

Macierz transponowana

In [29]:
np.transpose(A)

array([[ 2, -1],
       [ 4,  3]])

In [30]:
A.T

array([[ 2, -1],
       [ 4,  3]])

Rozw ukladow rownan

In [33]:
A = np.array([[2, 4], [1, -1]])
A

array([[ 2,  4],
       [ 1, -1]])

In [35]:
B = np.array([[10], [-1]])
B

array([[10],
       [-1]])

In [36]:
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
X

array([[1.],
       [2.]])

In [37]:
X.shape

(2, 1)